'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  DEFAULT: 'BMAP_DRIVING_POLICY_DEFAULT',
  FIRST_HIGHWAYS: 'BMAP_DRIVING_POLICY_FIRST_HIGHWAYS',
  AVOID_HIGHWAYS: 'BMAP_DRIVING_POLICY_AVOID_HIGHWAYS',
  AVOID_CONGESTION: 'BMAP_DRIVING_POLICY_AVOID_CONGESTION'
};