'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  CIRCLE: 'BMap_Symbol_SHAPE_CIRCLE',
  RECTANGLE: 'BMap_Symbol_SHAPE_RECTANGLE',
  RHOMBUS: 'BMap_Symbol_SHAPE_RHOMBUS',
  STAR: 'BMap_Symbol_SHAPE_STAR',
  BACKWARD_CLOSED_ARROW: 'BMap_Symbol_SHAPE_BACKWARD_CLOSED_ARROW',
  FORWARD_CLOSED_ARROW: 'BMap_Symbol_SHAPE_FORWARD_CLOSED_ARROW',
  BACKWARD_OPEN_ARROW: 'BMap_Symbol_SHAPE_BACKWARD_OPEN_ARROW',
  FORWARD_OPEN_ARROW: 'BMap_Symbol_SHAPE_FORWARD_OPEN_ARROW',
  POINT: 'BMap_Symbol_SHAPE_POINT',
  PLANE: 'BMap_Symbol_SHAPE_PLANE',
  CAMERA: 'BMap_Symbol_SHAPE_CAMERA',
  WARNING: 'BMap_Symbol_SHAPE_WARNING',
  SMILE: 'BMap_Symbol_SHAPE_SMILE',
  CLOCK: 'BMap_Symbol_SHAPE_CLOCK'
};