'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  RECOMMEND: 'BMAP_TRANSIT_POLICY_RECOMMEND',
  LEAST_TIME: 'BMAP_TRANSIT_POLICY_LEAST_TIME',
  LEAST_TRANSFER: 'BMAP_TRANSIT_POLICY_LEAST_TRANSFER',
  LEAST_WALKING: 'BMAP_TRANSIT_POLICY_LEAST_WALKING',
  AVOID_SUBWAYS: 'BMAP_TRANSIT_POLICY_AVOID_SUBWAYS',
  FIRST_SUBWAYS: 'BMAP_TRANSIT_POLICY_FIRST_SUBWAYS'
};