export default {
  CIRCLE: 'BMAP_POINT_SHAPE_CIRCLE',
  STAR: 'BMAP_POINT_SHAPE_STAR',
  SQUARE: 'BMAP_POINT_SHAPE_SQUARE',
  RHOMBUS: 'BMAP_POINT_SHAPE_RHOMBUS',
  WATERDROP: 'BMAP_POINT_SHAPE_WATERDROP',
};
